# Path to your oh-my-zsh installation.
### Path manipulation
# Make PATH a set instead of an array to dedup and speed up resolution
typeset -U PATH

if [[ -d "/usr/local/go/bin" ]] ; then
  path=("/usr/local/go/bin" $path)
fi

if [[ -d "$HOME/.jakeman/go/bin" ]] ; then
  path=("$HOME/.jakeman/go/bin" $path)
fi

if [[ -d "$HOME/.cargo/bin" ]] ; then
  path=("$HOME/.cargo/bin" $path)
fi

if [[ -d "/opt/homebrew/bin" ]] ; then
  path=("/opt/homebrew/bin" $path)
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  if [[ -d /opt/homebrew/opt/openjdk/bin ]] ; then
    path+=("/opt/homebrew/opt/openjdk/bin" $path)
  fi
fi

if [[ -d "$HOME/.rd/bin" ]] ; then
  path=("$HOME/.rd/bin" $path)
fi

### Add go get binaries
if whence -p go &>/dev/null ; then
  path=("$(go env GOPATH)/bin" $path)
fi

if [[ -d "$HOME/bin" ]] ; then
  path=("$HOME/bin" $path)
fi

if [[ -s "$HOME/.local/share/bob" ]] ; then
  path=("$HOME/.local/share/bob/nvim-bin/" $path)
fi

### oh-my-zsh
MY_ZSH_ROOT=$HOME/.dotfiles/rc.d/zsh
export ZSH=$MY_ZSH_ROOT/oh-my-zsh

ZSH_THEME="jakeman"

ZSH_CUSTOM=$MY_ZSH_ROOT/custom

DEFAULT_USER="$USER"

plugins=(
  1password
  bazel
  git
  golang
  kubectl
  ssh-agent
)

if whence -p gh &>/dev/null ; then
  plugins+=(gh)
fi

# if whence -p rg &>/dev/null ; then
#   plugins+=(ripgrep)
# fi

# if whence -p fdfind &>/dev/null ; then
#   plugins+=(fd)
# fi

if whence -p fzf &>/dev/null ; then
  plugins+=(fzf)
fi

### Aliases etc
alias dr='docker run --rm -t -i'
alias pyactive='source venv/bin/activate'

# go all in
export EDITOR=`which nvim`
alias vim=nvim

if (( $+commands[podman] )); then

 # If the completion file doesn't exist yet, we need to autoload it and
 # bind it to `podman`. Otherwise, compinit will have already done that.
 if [[ ! -f "$ZSH_CACHE_DIR/completions/_podman" ]]; then
   typeset -g -A _comps
   autoload -Uz _podman
   _comps[podman]=_podman
 fi

 podman completion zsh 2> /dev/null >| "$ZSH_CACHE_DIR/completions/_podman" &|
fi

source $ZSH/oh-my-zsh.sh

if [[ "xterm-kitty" == "$TERM" && ! -e "/usr/share/terminfo/x/xterm-kitty" ]] ; then
  # Rather than fully break, use the terminfo for a basic xterm if we don't
  # have the kitty terminfo installed
  # TODO: figure out a way to install the terminfo for kitty w/o installing x
  export TERM='xterm-256color'
fi

# Enable completion for bazelisk
alias bazel=bazelisk
compdef bazelisk=bazel
