# Path to your oh-my-zsh installation.
### Path manipulation
if [[ -d "/usr/local/go/bin" ]] ; then
  export PATH="/usr/local/go/bin:$PATH"
fi

if [[ -d "$HOME/.jakeman/go/bin" ]] ; then
  export PATH="$HOME/.jakeman/go/bin:$PATH"
fi

if [[ -d "$HOME/.cargo/bin" ]] ; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

if [[ -d "/opt/homebrew/bin" ]] ; then
  export PATH="/opt/homebrew/bin:$PATH"
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  if [[ -d /opt/homebrew/opt/openjdk/bin ]] ; then
    export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
  fi
fi

if [[ -d "$HOME/.rd/bin" ]] ; then
  export PATH="$HOME/.rd/bin:$PATH"
fi

### Add go get binaries
if whence -p go &>/dev/null ; then
  export PATH="$(go env GOPATH)/bin:$PATH"
fi

if [[ -d "$HOME/bin" ]] ; then
  export PATH="$HOME/bin:$PATH"
fi

### oh-my-zsh
MY_ZSH_ROOT=$HOME/.dotfiles/rc.d/zsh
export ZSH=$MY_ZSH_ROOT/oh-my-zsh

ZSH_THEME="jakeman"

ZSH_CUSTOM=$MY_ZSH_ROOT/custom

DEFAULT_USER="$USER"

plugins=(
  bazel
  docker
  git
  golang
  helm
  kubectl
  ssh-agent
)

if whence -p gh &>/dev/null ; then
  plugins+=(gh)
fi

if whence -p rg &>/dev/null ; then
  plugins+=(ripgrep)
fi

if whence -p fdfind &>/dev/null ; then
  plugins+=(fd)
fi

if whence -p fzf &>/dev/null ; then
  plugins+=(fzf)
fi

### Aliases etc
alias dr='docker run --rm -t -i'
alias pyactive='source venv/bin/activate'

# go all in
alias vim=nvim
export EDITOR=`which vim`

source $ZSH/oh-my-zsh.sh


if [[ "xterm-kitty" == "$TERM" && ! -e "/usr/share/terminfo/x/xterm-kitty" ]] ; then
  # Rather than fully break, use the terminfo for a basic xterm if we don't
  # have the kitty terminfo installed
  # TODO: figure out a way to install the terminfo for kitty w/o installing x
  export TERM='xterm-256color'
fi

# Enable completion for bazelisk
alias bazel=bazelisk
compdef bazelisk=bazel
