########## path manipulation ##########
# Make PATH a set instead of an array to dedup and speed up resolution
typeset -U PATH

if [[ -d "/usr/local/go/bin" ]] ; then
  path=("/usr/local/go/bin" $path)
fi

if [[ -d "$HOME/.jakeman/go/bin" ]] ; then
  path=("$HOME/.jakeman/go/bin" $path)
fi

if [[ -d "$HOME/.cargo/bin" ]] ; then
  path=("$HOME/.cargo/bin" $path)
fi

if [[ -d "$HOME/.rd/bin" ]] ; then
  path=("$HOME/.rd/bin" $path)
fi

# Add go get binaries
if whence -p go &>/dev/null ; then
  path=("$(go env GOPATH)/bin" $path)
fi

if [[ -d "$HOME/bin" ]] ; then
  path=("$HOME/bin" $path)
fi

if [[ -s "$HOME/.local/share/bob" ]] ; then
  path=("$HOME/.local/share/bob/nvim-bin/" $path)
fi

if [[ -s "$HOME/.pyenv" ]] ; then
  export PYENV_ROOT="$HOME/.pyenv"
  [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
fi

########## oh-my-zsh ##########
MY_ZSH_ROOT=$HOME/.dotfiles/rc.d/zsh
export ZSH=$MY_ZSH_ROOT/oh-my-zsh

ZSH_THEME="jakeman"

ZSH_CUSTOM=$MY_ZSH_ROOT/custom

DEFAULT_USER="$USER"

plugins=(
  1password
  bazel
  brew
  git
  golang
  kubectl
  podman
  rust
  ssh-agent
  virtualenv
)


if whence -p gh &>/dev/null ; then
  plugins+=(gh)
fi

# Default to no aliases from plugins
zstyle ':omz:plugins:*' aliases no

# Enable git vcs_info for my prompt
zstyle ':vcs_info:*' enable git

########## Aliases ##########
alias dr='docker run --rm -t -i'
alias pyactive='source venv/bin/activate'

# Use nvim
if whence -p nvim &>/dev/null ; then
export EDITOR=`which nvim`
alias vim=nvim
else
  export EDITOR=`which vim`
fi

source $ZSH/oh-my-zsh.sh

if [[ "xterm-kitty" == "$TERM" && ! -e "/usr/share/terminfo/x/xterm-kitty" ]] ; then
  # Rather than fully break, use the terminfo for a basic xterm if we don't
  # have the kitty terminfo installed
  # TODO: figure out a way to install the terminfo for kitty w/o installing x
  export TERM='xterm-256color'
fi

########## post-zsh load ########## 

# Use bazelisk for bazel and enable completion
alias bazel=bazelisk
compdef bazelisk=bazel

export VIRTUAL_ENV_DISABLE_PROMPT=1
