---
- name: Ensure oni config exists
  file:
    path: "{{ ansible_env.HOME }}/.config/oni2"
    state: directory
    mode: '755'
- name: symlink oni config files
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/rc.d/onivim/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/oni2/{{ item }}"
    state: link
  loop:
    - configuration.json
    - keybindings.json
