- name: Install gh cli apt keyring
  get_url:
    url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: u=rw,g=r,o=r
- name: Add gh cli apt repo
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
    dest: /etc/apt/sources.list.d/github-cli.list
    mode: 0644
    owner: root
    group: root
- name: Install non-x packages
  apt:
    name:
      - ansible
      - build-essential
      - cmake
      - exuberant-ctags
      - curl
      - fontconfig
      - gh
      - git
      - net-tools
      - python-is-python3
      - python3-dev
      - python3-pip
      - python3-venv
      - ruby-dev
      - shellcheck
      - tmux
      - vim-nox
      - virtualenv
      - zsh
    update_cache: true
    state: present
- name: Ensure jkaufman exists
  user:
    name: jkaufman
    comment: "Jake Kaufman"
    shell: /usr/bin/zsh
    groups: sudo
    append: true
- name: Install X11 packages
  apt:
    name:
      - kitty
      - lm-sensors
      - xautomation
      - xbindkeys
      - xclip
    update_cache: true
    state: present
