- name: Ensure {{ tmp_dir }}
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: '0755'
- name: Download nvm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh
    dest: "{{ tmp_dir }}/nvm_install.sh"
    mode: '0755'
  register: download
- name: Run nvim install
  ansible.builtin.command:
    cmd: "{{ download.dest }}"
    creates: "{{ ansible_env.HOME }}/.nvm"
- name: Run node install
  ansible.builtin.shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh \
    && nvm install {{ nodejs_version }} \
    && nvm alias default {{ nodejs_version }}
  args:
    executable: "/bin/bash"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/{{ nodejs_version }}"
