- name: Create bin/
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: '755'
- name: Build work venv
  pip:
    chdir: /home/jkaufman/.dotfiles/
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_python: python3
- name: symlink from venv to bin
  file:
    src: '/home/jkaufman/.dotfiles/venv/bin/{{ item }}'
    dest: '/home/jkaufman/bin/{{ item }}'
    state: link
  loop:
    - add-trailing-comma
    - ansible
    - ansible-config
    - ansible-connection
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-lint
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
    - autopep8
    - aws
    - black
    - flake8
    - isort
    - mypy
    - pip
    - pip-compile
    - pipenv
    - pre-commit
    - python3
    - pyupgrade
    - reorder-python-imports
    - tox
    - virtualenv
    - wheel
