- name: Ensure bin/
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: '0755'
- name: Build work venv
  pip:
    chdir: "{{ ansible_env.HOME }}/.dotfiles/"
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_python: python3
- name: Symlink binaries from venv to ~/bin
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/venv/bin/{{ item }}"
    dest: "{{ ansible_env.HOME }}/bin/{{ item }}"
    state: link
  loop:
    - add-trailing-comma
    - ansible-lint
    - autopep8
    - black
    - flake8
    - isort
    - mypy
    - pip
    - pip-compile
    - pipenv
    - pre-commit
    - python3
    - pyupgrade
    - qmk
    - reorder-python-imports
    - tox
    - virtualenv
    - wheel
